element = cmds.ls(sl = True)
destinationObject_tx = cmds.getAttr(element[0] + '.tx')
destinationObject_ty = cmds.getAttr(element[0] + '.ty')
destinationObject_tz = cmds.getAttr(element[0] + '.tz')
destinationObject_rx = cmds.getAttr(element[0] + '.rx')
destinationObject_ry = cmds.getAttr(element[0] + '.ry')
destinationObject_rz = cmds.getAttr(element[0] + '.rz')
cmds.setAttr(element[1] + '.tx', destinationObject_tx)
cmds.setAttr(element[1] + '.ty', destinationObject_ty)
cmds.setAttr(element[1] + '.tz', destinationObject_tz)
cmds.setAttr(element[1] + '.rx', destinationObject_rx)
cmds.setAttr(element[1] + '.ry', destinationObject_ry)
cmds.setAttr(element[1] + '.rz', destinationObject_rz)